name: example
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  two_way_scrollable:
    path: ../
  random_color: ^1.0.6-nullsafety
  collection: ^1.17.0
  material_design_icons_flutter: ^6.0.7096
  window_size:
    git:
      url: git@github.com:google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.14.0
  equatable: ^2.0.3
  meta: ^1.8.0

flutter:
  uses-material-design: true
