name: two_way_scrollable
description: A set of two-way growable widgets for Flutter that properly fill the viewport even if there is not enough content.
homepage: https://github.com/s0nerik/two_way_scrollable
version: 0.1.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
